title: Devaland Automation Agency
description: Transform Your Business with Goal-Driven AI Solutions
baseurl: ""
url: ""
email: office@devaland.com
phone: "+40 (721) 269 312"
social:
  linkedin: "https://www.linkedin.com/in/marius-andronie"
  instagram: "https://www.instagram.com/digitalvampire13/"
